apiVersion: v1
kind: Service
metadata:
  name: hermes-backend
  labels:
    app: hermes
    component: backend
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: hermes
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: hermes-frontend
  labels:
    app: hermes
    component: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hermes
    component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: hermes-db
  labels:
    app: hermes
    component: db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: hermes
    component: db
